# Generated by Django 6.1.1 on 2026-09-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medewerkers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medewerker',
            name='functie',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
