# Generated by Django 6.1.1 on 2026-09-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medewerkers', '0002_medewerker_functie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medewerker',
            name='rol',
            field=models.CharField(choices=[('medewerker', 'Medewerker'), ('eigenaar', 'Eigenaar'), ('beheerder', 'Systeembeheerder')], default='medewerker', max_length=20),
        ),
    ]
