# Generated by Django 6.1.1 on 2026-09-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medewerkers', '0003_alter_medewerker_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='medewerker',
            name='aanhanger',
            field=models.BooleanField(default=False, help_text='Mag met een zware aanhanger rijden.', verbose_name='aanhanger (BE)'),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='adres',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='noodcontact_naam',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='noodcontact_relatie',
            field=models.CharField(blank=True, help_text='Bijvoorbeeld partner, moeder, broer.', max_length=40),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='noodcontact_telefoon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='rijbewijs',
            field=models.CharField(blank=True, choices=[('', 'Geen'), ('B', 'B — personenauto'), ('C', 'C — vrachtwagen')], max_length=2),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='woonplaats',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='medewerker',
            name='telefoon',
            field=models.CharField(blank=True, max_length=20, verbose_name='mobiel nummer'),
        ),
    ]
