# Generated by Django 6.1.1 on 2026-09-26 09:52

import medewerkers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medewerkers', '0003_medewerker_aanhanger_medewerker_adres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medewerker',
            name='profielfoto',
            field=models.ImageField(blank=True, upload_to=medewerkers.models.profielfoto_pad),
        ),
    ]
