# Generated by Django 6.1.1 on 2026-10-01 12:37

import medewerkers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medewerkers', '0005_rijbewijzen'),
    ]

    operations = [
        migrations.AddField(
            model_name='medewerker',
            name='vaste_werkdagen',
            field=models.JSONField(blank=True, default=medewerkers.models.standaard_werkdagen),
        ),
    ]
