# Generated by Django 6.1.1 on 2026-10-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medewerkers', '0006_vaste_werkdagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='medewerker',
            name='backup_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='back-up naar'),
        ),
    ]
