# Generated by Django 6.1.1 on 2026-10-03 07:41

import django.contrib.auth.models
import medewerkers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medewerkers', '0007_backup_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medewerker',
            options={'default_manager_name': 'alle', 'ordering': ['first_name', 'last_name', 'username'], 'verbose_name': 'medewerker', 'verbose_name_plural': 'medewerkers'},
        ),
        migrations.AlterModelManagers(
            name='medewerker',
            managers=[
                ('alle', django.contrib.auth.models.UserManager()),
                ('objects', medewerkers.models.ZichtbareMedewerkers()),
            ],
        ),
        migrations.AddField(
            model_name='medewerker',
            name='verborgen',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
