# Generated by Django 6.1.1 on 2026-10-03 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medewerkers', '0008_verborgen_beheeraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medewerker',
            name='kleur',
            field=models.CharField(blank=True, help_text='Hexkleur waarmee deze medewerker in het planbord wordt getoond.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Kies een kleur als #RRGGBB, bijvoorbeeld #5f7d12.')]),
        ),
    ]
