# Generated by Django 6.1.1 on 2026-10-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medewerkers', '0009_kleur_controleren'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soort', models.CharField(choices=[('inloggen', 'Mislukt inloggen'), ('reset', 'Wachtwoord vergeten')], max_length=20)),
                ('sleutel', models.CharField(max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('tijdstip', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'poging',
                'verbose_name_plural': 'pogingen',
                'indexes': [models.Index(fields=['soort', 'sleutel', 'tijdstip'], name='medewerkers_soort_7ac637_idx')],
            },
        ),
    ]
