# Generated by Django 6.1.1 on 2026-09-07 12:57

import klussen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bijlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestand', models.FileField(upload_to=klussen.models.bijlage_pad)),
                ('soort', models.CharField(choices=[('foto', 'Foto'), ('document', 'Document')], default='foto', max_length=20)),
                ('toelichting', models.TextField(blank=True)),
                ('toegevoegd_op', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'bijlage',
                'verbose_name_plural': 'bijlagen',
                'ordering': ['-toegevoegd_op'],
            },
        ),
        migrations.CreateModel(
            name='Klus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=120)),
                ('soort', models.CharField(choices=[('aanleg', 'Aanleg'), ('onderhoud', 'Onderhoud')], default='aanleg', max_length=20)),
                ('opdrachtgever', models.CharField(blank=True, max_length=120)),
                ('adres', models.CharField(blank=True, max_length=200)),
                ('plaats', models.CharField(blank=True, max_length=80)),
                ('kleur', models.CharField(blank=True, help_text='Hexkleur van de blokken in het planbord.', max_length=7)),
                ('actief', models.BooleanField(default=True)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'klus',
                'verbose_name_plural': 'klussen',
                'ordering': ['-actief', 'naam'],
            },
        ),
    ]
