# Generated by Django 6.1.1 on 2026-09-07 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klussen', '0001_initial'),
        ('uren', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bijlage',
            name='toegevoegd_door',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bijlagen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bijlage',
            name='uurblok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bijlagen', to='uren.uurblok'),
        ),
        migrations.AddField(
            model_name='bijlage',
            name='klus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bijlagen', to='klussen.klus'),
        ),
    ]
