# Generated by Django 6.1.1 on 2026-09-13 12:17

import klussen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klussen', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bijlage',
            name='originele_naam',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bijlage',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to=klussen.models.thumbnail_pad),
        ),
    ]
