# Generated by Django 6.1.1 on 2026-09-13 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klussen', '0003_bijlage_originele_naam_bijlage_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bijlage',
            options={'ordering': ['-datum', '-toegevoegd_op'], 'verbose_name': 'bijlage', 'verbose_name_plural': 'bijlagen'},
        ),
        migrations.AddField(
            model_name='bijlage',
            name='datum',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
