# Generated by Django 6.1.1 on 2026-09-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klussen', '0004_alter_bijlage_options_bijlage_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='klus',
            name='beschrijving',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='klus',
            name='startdatum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
