# Generated by Django 6.1.1 on 2026-09-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klussen', '0005_klus_beschrijving_klus_startdatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='klus',
            name='afgerond_op',
            field=models.DateField(blank=True, null=True),
        ),
    ]
