# Generated by Django 6.1.1 on 2026-09-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klussen', '0007_kleur_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bijlage',
            name='batch',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
