# Generated by Django 6.1.1 on 2026-09-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klussen', '0008_bijlage_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klus',
            name='soort',
            field=models.CharField(choices=[('aanleg', 'Eenmalig'), ('onderhoud', 'Onderhoud')], default='aanleg', max_length=20),
        ),
    ]
