# Generated by Django 6.1.1 on 2026-10-01 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klussen', '0010_plaatjes_als_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField(max_length=2000)),
                ('geschreven_op', models.DateTimeField(auto_now_add=True)),
                ('geschreven_door', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notities', to=settings.AUTH_USER_MODEL)),
                ('klus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notities', to='klussen.klus')),
            ],
            options={
                'verbose_name': 'notitie',
                'verbose_name_plural': 'notities',
                'ordering': ['-geschreven_op'],
            },
        ),
    ]
