# Generated by Django 6.1.1 on 2026-10-01 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klussen', '0011_notitie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bijlage',
            name='zichtbaar_voor',
            field=models.ManyToManyField(blank=True, related_name='zichtbare_bijlagen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='klus',
            name='soort',
            field=models.CharField(choices=[('aanleg', 'Aanleg'), ('onderhoud', 'Onderhoud')], default='aanleg', max_length=20),
        ),
    ]
