# Generated by Django 6.1.1 on 2026-10-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klussen', '0012_bijlage_zichtbaar_voor_alter_klus_soort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klus',
            name='soort',
            field=models.CharField(choices=[('aanleg', 'Aanleg'), ('onderhoud', 'Onderhoud'), ('van_ee', 'Van Ee')], default='aanleg', max_length=20),
        ),
    ]
