# Generated by Django 6.1.1 on 2026-10-03 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klussen', '0013_alter_klus_soort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klus',
            name='kleur',
            field=models.CharField(blank=True, help_text='Hexkleur van de blokken in het planbord.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Kies een kleur als #RRGGBB, bijvoorbeeld #5f7d12.')]),
        ),
    ]
