# Generated by Django 6.1.1 on 2026-10-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uren', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uurblok',
            name='extra_werk',
            field=models.TextField(blank=True),
        ),
    ]
