# Generated by Django 6.1.1 on 2026-10-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uren', '0002_uurblok_extra_werk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dagnotitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(unique=True)),
                ('tekst', models.CharField(max_length=120)),
                ('gewijzigd_op', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'dagnotitie',
                'verbose_name_plural': 'dagnotities',
                'ordering': ['datum'],
            },
        ),
        migrations.AddField(
            model_name='aanwezigheid',
            name='reden',
            field=models.CharField(blank=True, choices=[('vakantie', 'Vakantie'), ('ziek', 'Ziek'), ('vrij', 'Vrij'), ('anders', 'Anders')], max_length=20),
        ),
    ]
