# Generated by Django 6.1.1 on 2026-10-01 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klussen', '0013_alter_klus_soort'),
        ('uren', '0003_werkplanning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('klus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inzet', to='klussen.klus')),
                ('medewerker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inzet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inzet',
                'verbose_name_plural': 'inzet',
                'ordering': ['datum', 'aangemaakt_op'],
                'constraints': [models.UniqueConstraint(fields=('medewerker', 'datum', 'klus'), name='een_klus_eenmaal_per_dag')],
            },
        ),
    ]
