# Generated by Django 6.1.1 on 2026-10-01 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klussen', '0013_alter_klus_soort'),
        ('uren', '0005_afwezig_zonder_klus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klusdag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('notitie', models.CharField(blank=True, max_length=120)),
                ('gewijzigd_op', models.DateTimeField(auto_now=True)),
                ('klus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klusdagen', to='klussen.klus')),
            ],
            options={
                'verbose_name': 'klusdag',
                'verbose_name_plural': 'klusdagen',
                'ordering': ['datum'],
                'constraints': [models.UniqueConstraint(fields=('klus', 'datum'), name='een_klusdag_per_dag')],
            },
        ),
    ]
