# Generated by Django 6.1.1 on 2026-09-07 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klussen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aanwezigheid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('aanwezig', models.BooleanField(default=True)),
                ('opmerking', models.CharField(blank=True, max_length=200)),
                ('gewijzigd_op', models.DateTimeField(auto_now=True)),
                ('medewerker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aanwezigheid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aanwezigheid',
                'verbose_name_plural': 'aanwezigheid',
                'ordering': ['-datum'],
                'constraints': [models.UniqueConstraint(fields=('medewerker', 'datum'), name='een_registratie_per_dag')],
            },
        ),
        migrations.CreateModel(
            name='Uurblok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('begintijd', models.TimeField()),
                ('eindtijd', models.TimeField()),
                ('toelichting', models.TextField(blank=True)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('gewijzigd_op', models.DateTimeField(auto_now=True)),
                ('klus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uurblokken', to='klussen.klus')),
                ('medewerker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uurblokken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uurblok',
                'verbose_name_plural': 'uurblokken',
                'ordering': ['-datum', 'begintijd'],
                'indexes': [models.Index(fields=['datum', 'medewerker'], name='uren_uurblo_datum_33f93c_idx'), models.Index(fields=['klus', 'datum'], name='uren_uurblo_klus_id_3b790b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('eindtijd__gt', models.F('begintijd'))), name='eindtijd_na_begintijd')],
            },
        ),
    ]
